// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace AssemblyCSharp
{
	[TestFixture()]
	public class ApiTests
	{
		[Test()]
		public void gameStateTest ()
		{
			RemoteApi api = RemoteApi.getInstance ("user", "pass");
			Assert.AreSame (null, api.getGameState (0));
		}
	}
}

